import LegalDocument from "../legal-document";
import { SITE_URL } from "@/lib/site";

export const metadata = { title: "Política de Cookies", description: "Cookies necessários e analíticos usados pela CandTech.", alternates: { canonical: `${SITE_URL}/cookies` } };
export default function CookiesPage() { return <LegalDocument eyebrow="PREFERÊNCIAS" title="Política de Cookies" summary="Cookies necessários mantêm a conta segura. Cookies analíticos são opcionais, ficam desligados por padrão e só são carregados após uma escolha afirmativa.">
  <h2>Cookies necessários</h2><p><code>finsight_token</code> mantém a sessão autenticada por até 8 horas. É HttpOnly, Secure em produção e SameSite=Lax. Sua base é a execução do serviço e a segurança. Não pode ser desativado durante o uso autenticado porque identifica a sessão com segurança.</p>
  <h2>Análise opcional</h2><p>Após “Aceitar análise”, o Google Analytics pode criar <code>_ga</code> e <code>_ga_*</code> para distinguir navegadores e medir páginas, origem aproximada e eventos agregados. Esses cookies podem durar até dois anos, sujeitos à configuração do Google e à exclusão pelo usuário. A base é o consentimento. A CandTech não envia nome, e-mail, tipo de conta, valores, dados de pagamento, documentos ou conteúdo do ERP.</p>
  <p>O site usa o modo básico de consentimento: a tag do Google Analytics não é carregada e nenhum dado é enviado à ferramenta antes da aceitação. O consentimento exibido não autoriza publicidade personalizada, Google Signals nem vinculação com plataformas de anúncios.</p>
  <h2>Escolha e revogação</h2><p>A escolha é guardada no armazenamento local do navegador sob a chave <code>candtech_analytics_consent_v1</code> até ser alterada ou apagada. “Usar só o necessário” fica disponível junto de “Aceitar análise”. O botão “Cookies” permite alterar a preferência a qualquer momento. Ao recusar, a aplicação deixa de carregar a ferramenta e remove os cookies analíticos acessíveis do domínio; a recusa não limita o serviço.</p>
  <h2>Configuração do navegador</h2><p>O navegador também permite apagar ou bloquear cookies. Bloquear o cookie necessário impede o login. Mudanças de fornecedores ou finalidades exigirão atualização desta política e, quando necessário, novo consentimento.</p>
</LegalDocument>; }
